# Imports
from django.urls import path
from apps.pokemon.views import (
    AbilityRouteView,
    AbilitiesView,
    CharacteristicRouteView,
    CharacteristicsView,
    EggGroupRouteView,
    EggGroupsView,
    GenderRouteView,
    GenderView,
    GrowthRateRouteView,
    GrowthRatesView,
    NatureRouteView,
    NaturesView,
    PokeathlonStatRouteView,
    PokeathlonStatsView,
    PokemonRouteView,
    PokemonView,
    PokemonColorRouteView,
    PokemonColorsView,
    PokemonFormRouteView,
    PokemonFormsView,
    PokemonHabitatRouteView,
    PokemonHabitatsView,
    PokemonShapeRouteView,
    PokemonShapesView,
    PokemonSpeciesRouteView,
    PokemonSpeciesView,
    StatRouteView,
    StatsView,
    TypeRouteView,
    TypesView,
)


# Add the path to router
urlpatterns = [
    path(
        "ability/",
        AbilityRouteView.as_view(),
        name="api--ability-routes",
    ),
    path(
        "ability/<int:entity_id>/",
        AbilitiesView.as_view(),
        name="api--abilities",
    ),
    path(
        "characteristic/",
        CharacteristicRouteView.as_view(),
        name="api--characteristic-routes",
    ),
    path(
        "characteristic/<int:entity_id>/",
        CharacteristicsView.as_view(),
        name="api--characteristics",
    ),
    path(
        "egg-group/",
        EggGroupRouteView.as_view(),
        name="api--egg-group-routes",
    ),
    path(
        "egg-group/<int:entity_id>/",
        EggGroupsView.as_view(),
        name="api--egg-groups",
    ),
    path(
        "gender/",
        GenderRouteView.as_view(),
        name="api--gender-routes",
    ),
    path(
        "gender/<int:entity_id>/",
        GenderView.as_view(),
        name="api--genders",
    ),
    path(
        "growth-rate/",
        GrowthRateRouteView.as_view(),
        name="api--growth-rate-routes",
    ),
    path(
        "growth-rate/<int:entity_id>/",
        GrowthRatesView.as_view(),
        name="api--growth-rates",
    ),
    path(
        "nature/",
        NatureRouteView.as_view(),
        name="api--nature-routes",
    ),
    path(
        "nature/<int:entity_id>/",
        NaturesView.as_view(),
        name="api--natures",
    ),
    path(
        "pokeathlon-stat/",
        PokeathlonStatRouteView.as_view(),
        name="api--pokeathlon-stat-routes",
    ),
    path(
        "pokeathlon-stat/<int:entity_id>/",
        PokeathlonStatsView.as_view(),
        name="api--pokeathlon-stats",
    ),
    path(
        "pokemon/",
        PokemonRouteView.as_view(),
        name="api--pokemon-routes",
    ),
    path(
        "pokemon/<int:entity_id>/",
        PokemonView.as_view(),
        name="api--pokemons",
    ),
    path(
        "pokemon-color/",
        PokemonColorRouteView.as_view(),
        name="api--pokemon-color-routes",
    ),
    path(
        "pokemon-color/<int:entity_id>/",
        PokemonColorsView.as_view(),
        name="api--pokemon-colors",
    ),
    path(
        "pokemon-form/",
        PokemonFormRouteView.as_view(),
        name="api--pokemon-form-routes",
    ),
    path(
        "pokemon-form/<int:entity_id>/",
        PokemonFormsView.as_view(),
        name="api--pokemon-forms",
    ),
    path(
        "pokemon-habitat/",
        PokemonHabitatRouteView.as_view(),
        name="api--pokemon-habitat-routes",
    ),
    path(
        "pokemon-habitat/<int:entity_id>/",
        PokemonHabitatsView.as_view(),
        name="api--pokemon-habitats",
    ),
    path(
        "pokemon-shape/",
        PokemonShapeRouteView.as_view(),
        name="api--pokemon-shape-routes",
    ),
    path(
        "pokemon-shape/<int:entity_id>/",
        PokemonShapesView.as_view(),
        name="api--pokemon-shapes",
    ),
    path(
        "pokemon-species/",
        PokemonSpeciesRouteView.as_view(),
        name="api--pokemon-species-routes",
    ),
    path(
        "pokemon-species/<int:entity_id>/",
        PokemonSpeciesView.as_view(),
        name="api--pokemon-species",
    ),
    path(
        "stat/",
        StatRouteView.as_view(),
        name="api--stat-routes",
    ),
    path(
        "stat/<int:entity_id>/",
        StatsView.as_view(),
        name="api--stats",
    ),
    path(
        "type/",
        TypeRouteView.as_view(),
        name="api--type-routes",
    ),
    path(
        "type/<int:entity_id>/",
        TypesView.as_view(),
        name="api--types",
    ),
]
